experiment:
  name: "/Shared/{{cookiecutter.project_name}}"
  tracking_uri: "sqlite:///mlruns.db"
  artifact_location: "./mlruns"

model_registry:
  # Specifies the name of the Registered Model to use when registering a trained model to
  # the MLflow Model Registry
  model_name: {%raw-%}{{{%endraw%}MODEL_NAME|default('{{cookiecutter.project_name}}_model'){%raw-%}}}{%endraw%}

# Override the default train / validation / test dataset split ratios
SPLIT_RATIOS: [0.80, 0.10, 0.10]

INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/mlp-regression-template#ingest-step
  using: parquet
  location: "./data/sample.parquet"

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/mlp-regression-template#batch-scoring
  using: parquet
  location: "./data/sample.parquet"

PREDICT_OUTPUT_CONFIG:
  # For different options please read: https://github.com/mlflow/mlp-regression-template#predict-step
  using: parquet
  location: "./data/sample_output.parquet"
