# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under {{cookiecutter.project_name_alphanumeric_underscore}}/databricks-resource/*
# and {{cookiecutter.project_name_alphanumeric_underscore}}/bundle.yml with prod environment configs,
# when PRs are merged into the release branch
name: Bundle Deployment for {{cookiecutter.project_name}} Prod

on:
  push:
    branches:
      - '{{cookiecutter.release_branch}}'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./{{cookiecutter.project_name_alphanumeric_underscore}}

env:
  # This token is required until databricks/bricks repo is open to public
  BRICKS_REPO_TOKEN: {% raw %}${{ secrets.BRICKS_REPO_GITHUB_TOKEN }}{% endraw %}
  DATABRICKS_TOKEN: {% raw %}${{ secrets.PROD_WORKSPACE_TOKEN }}{% endraw %}

jobs:
  prod:
    concurrency: {{cookiecutter.project_name}}-prod-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-bricks@main
        with:
          token: {% raw %}${{ env.BRICKS_REPO_TOKEN }}{% endraw %}
      - name: Validate Bundle For Prod Environment
        id: validate
        run: |
          bricks bundle validate -e prod
      - name: Deploy Bundle to Prod Environment
        id: deploy
        run: |
          bricks bundle deploy -e prod
