name: Run checks
on:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install act
        run: |
          # Install act
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          echo "-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
          -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
          -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04" > ~/.actrc
          echo "PATH=$PATH:$(pwd)/bin" >> "$GITHUB_ENV"
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r dev-requirements.txt
      - name: Run tests with pytest
        run: |
          pytest tests --large -vv --black
